name: "Deploy on Comment"

on:
  issue_comment:
    types: [created]
# && contains(github.event.comment.body, '/unleash the kraken')
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          echo "Deploying... ${{github.ref}}  ${{github.event.comment.body}}"
