name: Testing Loading Env from file

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: tflint
        uses: ./.github/actions/tflint

      - name: Validate Everything
        shell: bash
        run: echo 'Great'