name: Pipeline for Timeoff - Project

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Loading
        if: startsWith(github.ref, 'refs/heads/dev')
        env:
          ENV_FILE: dev.env
        run: |
          source $ENV_FILE
          echo "Loaded environment variables from $ENV_FILE"
      - name: Use environment variables
        run: echo $WHERE $SCARE # Use the environment variables loaded from the environment file


      # - name: Set environment variables
      #   run: |
      #     if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
      #         echo "WHERE=prod" >> "$GITHUB_ENV"
      #         echo "SCARE=true" >> "$GITHUB_ENV"
      #         source prod.env
      #     else
      #         echo "WHERE=dev" >> "$GITHUB_ENV"
      #         echo "SCARE=false" >> "$GITHUB_ENV"
      #         source dev.env
      #     fi
      # - name: Using the environment variables
      #   run: echo "I am in $WHERE and the answer it is $SCARE that I am scared"