name: Testing Loading Env from file

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:

env:
  WHERE: default
  SCARE: default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Import environment variables from a file - PROD
        id: import-env-main
        shell: bash
        run: cat prod.env >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'
      - name: Import environment variables from a file - DEV
        id: import-env-dev
        shell: bash
        run: cat dev.env >> $GITHUB_ENV
        if: github.ref == 'refs/heads/dev'
      - name: Import environment variables from a file - DEV
        id: import-env-integration
        shell: bash
        run: cat dev.env >> $GITHUB_ENV
        if: github.ref == 'refs/heads/integration'
      - name: Testing Environment variables - SL (Integration)
        run: echo $WHERE $SCARE ${{github.ref}}